name: Trigger test-widget job on Bitrise!

on:
  pull_request:
    types: [ synchronize ]

jobs:
  trigger_test_widget:
    if: contains(github.event.pull_request.labels.*.name, 'run widget test')
    runs-on: ubuntu-latest
    name: trigger_test_widget
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Trigger the test widget job on bitrise
      run: |
        cat $GITHUB_EVENT_PATH
